package com.nh.biz.domain;

public class GroupDept {
	public GroupDept(){
	}
	
	public GroupDept(Integer grpId,Integer deptId){
		this.grpId = grpId;
		this.deptId = deptId;
	}
	
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column Resource_grp_dept.GRP_ID
     *
     * @abatorgenerated Mon Mar 19 18:23:55 CST 2012
     */
    private Integer grpId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column Resource_grp_dept.DEPT_ID
     *
     * @abatorgenerated Mon Mar 19 18:23:55 CST 2012
     */
    private Integer deptId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column Resource_grp_dept.ID
     *
     * @return the value of Resource_grp_dept.ID
     *
     * @abatorgenerated Mon Mar 19 18:23:55 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column Resource_grp_dept.ID
     *
     * @param id the value for Resource_grp_dept.ID
     *
     * @abatorgenerated Mon Mar 19 18:23:55 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column Resource_grp_dept.GRP_ID
     *
     * @return the value of Resource_grp_dept.GRP_ID
     *
     * @abatorgenerated Mon Mar 19 18:23:55 CST 2012
     */
    public Integer getGrpId() {
        return grpId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column Resource_grp_dept.GRP_ID
     *
     * @param grpId the value for Resource_grp_dept.GRP_ID
     *
     * @abatorgenerated Mon Mar 19 18:23:55 CST 2012
     */
    public void setGrpId(Integer grpId) {
        this.grpId = grpId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column Resource_grp_dept.DEPT_ID
     *
     * @return the value of Resource_grp_dept.DEPT_ID
     *
     * @abatorgenerated Mon Mar 19 18:23:55 CST 2012
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column Resource_grp_dept.DEPT_ID
     *
     * @param deptId the value for Resource_grp_dept.DEPT_ID
     *
     * @abatorgenerated Mon Mar 19 18:23:55 CST 2012
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}
