package com.nh.biz.domain;

import java.util.Date;

public class ResourceApproval {
	  /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.id
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.actDeptId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private Integer actdeptid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.actDeptName
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private String actdeptname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.resourceId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private Integer resourceid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.titleId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private Integer titleid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.resourceName
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private String filetype;
    private String actor;
    private Integer actorid;
    private Date sendTime;
    
    private String resourcename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.checkerId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private Integer checkerid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.checkerName
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private String checkername;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.checkTime
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private String checktime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.comments
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private String comments;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceApproval.result
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    private Integer result;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.id
     *
     * @return the value of ResourceApproval.id
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.id
     *
     * @param id the value for ResourceApproval.id
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.actDeptId
     *
     * @return the value of ResourceApproval.actDeptId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public Integer getActdeptid() {
        return actdeptid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.actDeptId
     *
     * @param actdeptid the value for ResourceApproval.actDeptId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setActdeptid(Integer actdeptid) {
        this.actdeptid = actdeptid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.actDeptName
     *
     * @return the value of ResourceApproval.actDeptName
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public String getActdeptname() {
        return actdeptname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.actDeptName
     *
     * @param actdeptname the value for ResourceApproval.actDeptName
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setActdeptname(String actdeptname) {
        this.actdeptname = actdeptname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.resourceId
     *
     * @return the value of ResourceApproval.resourceId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.resourceId
     *
     * @param resourceid the value for ResourceApproval.resourceId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.titleId
     *
     * @return the value of ResourceApproval.titleId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public Integer getTitleid() {
        return titleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.titleId
     *
     * @param titleid the value for ResourceApproval.titleId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setTitleid(Integer titleid) {
        this.titleid = titleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.resourceName
     *
     * @return the value of ResourceApproval.resourceName
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public String getResourcename() {
        return resourcename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.resourceName
     *
     * @param resourcename the value for ResourceApproval.resourceName
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setResourcename(String resourcename) {
        this.resourcename = resourcename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.checkerId
     *
     * @return the value of ResourceApproval.checkerId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public Integer getCheckerid() {
        return checkerid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.checkerId
     *
     * @param checkerid the value for ResourceApproval.checkerId
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setCheckerid(Integer checkerid) {
        this.checkerid = checkerid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.checkerName
     *
     * @return the value of ResourceApproval.checkerName
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public String getCheckername() {
        return checkername;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.checkerName
     *
     * @param checkername the value for ResourceApproval.checkerName
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setCheckername(String checkername) {
        this.checkername = checkername;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.checkTime
     *
     * @return the value of ResourceApproval.checkTime
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public String getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.checkTime
     *
     * @param checktime the value for ResourceApproval.checkTime
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setChecktime(String checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.comments
     *
     * @return the value of ResourceApproval.comments
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.comments
     *
     * @param comments the value for ResourceApproval.comments
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceApproval.result
     *
     * @return the value of ResourceApproval.result
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceApproval.result
     *
     * @param result the value for ResourceApproval.result
     *
     * @abatorgenerated Tue Mar 27 21:36:22 CST 2012
     */
    public void setResult(Integer result) {
        this.result = result;
    }

	public String getFiletype() {
		return filetype;
	}

	public void setFiletype(String filetype) {
		this.filetype = filetype;
	}

	public String getActor() {
		return actor;
	}

	public void setActor(String actor) {
		this.actor = actor;
	}

	public Integer getActorid() {
		return actorid;
	}

	public void setActorid(Integer actorid) {
		this.actorid = actorid;
	}

	public Date getSendTime() {
		return sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}
}
