package com.nh.biz.domain;

import java.util.ArrayList;
import java.util.List;

import org.hibernate.validator.constraints.NotEmpty;

import com.nh.biz.domain.system.Department;


	public class ResourceGroup {
	    /**
	     * This field was generated by Abator for iBATIS.
	     * This field corresponds to the database column ResourceGroup.ID
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    private Integer id;

	    /**
	     * This field was generated by Abator for iBATIS.
	     * This field corresponds to the database column ResourceGroup.GRP_NAME
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    @NotEmpty(message="目录名称不能为空！")
	    private String grpName;

	    /**
	     * This field was generated by Abator for iBATIS.
	     * This field corresponds to the database column ResourceGroup.GRP_DESC
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    private String grpDesc;

	    /**
	     * This field was generated by Abator for iBATIS.
	     * This field corresponds to the database column ResourceGroup.CREATE_DEPTID
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    private Integer createDeptid;
	    
	    private List<Department> departments = new ArrayList<Department>();
	    private List<Integer> departmentIds  = new ArrayList<Integer>();
	    
	    public List<Integer> getInputIds(){
	    	return departmentIds;
	    }
	    public void setDepartmentIds(List<Integer> departmentIds){
	    	this.departmentIds = departmentIds;
	    }

	    public List<Department> getDepartments() {
			return departments;
		}

		public void setDepartments(List<Department> departments) {
			this.departments = departments;
		}

		
		public List<Integer> getDepartmentIds(){
			List<Integer> departmentIds = new ArrayList<Integer>();
			for(Department dept : departments){
				departmentIds.add(dept.getDeptId());
			}
			return departmentIds;
		}
		/**
	     * This method was generated by Abator for iBATIS.
	     * This method returns the value of the database column ResourceGroup.ID
	     *
	     * @return the value of ResourceGroup.ID
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    public Integer getId() {
	        return id;
	    }

	    /**
	     * This method was generated by Abator for iBATIS.
	     * This method sets the value of the database column ResourceGroup.ID
	     *
	     * @param id the value for ResourceGroup.ID
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    public void setId(Integer id) {
	        this.id = id;
	    }

	    /**
	     * This method was generated by Abator for iBATIS.
	     * This method returns the value of the database column ResourceGroup.GRP_NAME
	     *
	     * @return the value of ResourceGroup.GRP_NAME
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    public String getGrpName() {
	        return grpName;
	    }

	    /**
	     * This method was generated by Abator for iBATIS.
	     * This method sets the value of the database column ResourceGroup.GRP_NAME
	     *
	     * @param grpName the value for ResourceGroup.GRP_NAME
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    public void setGrpName(String grpName) {
	        this.grpName = grpName;
	    }

	    /**
	     * This method was generated by Abator for iBATIS.
	     * This method returns the value of the database column ResourceGroup.GRP_DESC
	     *
	     * @return the value of ResourceGroup.GRP_DESC
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    public String getGrpDesc() {
	        return grpDesc;
	    }

	    /**
	     * This method was generated by Abator for iBATIS.
	     * This method sets the value of the database column ResourceGroup.GRP_DESC
	     *
	     * @param grpDesc the value for ResourceGroup.GRP_DESC
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    public void setGrpDesc(String grpDesc) {
	        this.grpDesc = grpDesc;
	    }

	    /**
	     * This method was generated by Abator for iBATIS.
	     * This method returns the value of the database column ResourceGroup.CREATE_DEPTID
	     *
	     * @return the value of ResourceGroup.CREATE_DEPTID
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    public Integer getCreateDeptid() {
	        return createDeptid;
	    }

	    /**
	     * This method was generated by Abator for iBATIS.
	     * This method sets the value of the database column ResourceGroup.CREATE_DEPTID
	     *
	     * @param createDeptid the value for ResourceGroup.CREATE_DEPTID
	     *
	     * @abatorgenerated Sat Mar 10 21:04:54 CST 2012
	     */
	    public void setCreateDeptid(Integer createDeptid) {
	        this.createDeptid = createDeptid;
	    }


	}
