package com.nh.biz.domain;

import java.util.Date;

public class ResourceTemplate {
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceTemplate.id
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceTemplate.titleId
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    private Integer titleid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceTemplate.tmpName
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    private String tmpname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceTemplate.fileDir
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    private String filedir;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceTemplate.fileName
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    private String filename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceTemplate.fileType
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    private String filetype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceTemplate.fileRealName
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    private String filerealname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceTemplate.uploadTime
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    private Date uploadtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ResourceTemplate.remark
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    private String remark;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceTemplate.id
     *
     * @return the value of ResourceTemplate.id
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceTemplate.id
     *
     * @param id the value for ResourceTemplate.id
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceTemplate.titleId
     *
     * @return the value of ResourceTemplate.titleId
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public Integer getTitleid() {
        return titleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceTemplate.titleId
     *
     * @param titleid the value for ResourceTemplate.titleId
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public void setTitleid(Integer titleid) {
        this.titleid = titleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceTemplate.tmpName
     *
     * @return the value of ResourceTemplate.tmpName
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public String getTmpname() {
        return tmpname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceTemplate.tmpName
     *
     * @param tmpname the value for ResourceTemplate.tmpName
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public void setTmpname(String tmpname) {
        this.tmpname = tmpname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceTemplate.fileDir
     *
     * @return the value of ResourceTemplate.fileDir
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public String getFiledir() {
        return filedir;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceTemplate.fileDir
     *
     * @param filedir the value for ResourceTemplate.fileDir
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public void setFiledir(String filedir) {
        this.filedir = filedir;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceTemplate.fileName
     *
     * @return the value of ResourceTemplate.fileName
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceTemplate.fileName
     *
     * @param filename the value for ResourceTemplate.fileName
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceTemplate.fileType
     *
     * @return the value of ResourceTemplate.fileType
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceTemplate.fileType
     *
     * @param filetype the value for ResourceTemplate.fileType
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceTemplate.fileRealName
     *
     * @return the value of ResourceTemplate.fileRealName
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public String getFilerealname() {
        return filerealname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceTemplate.fileRealName
     *
     * @param filerealname the value for ResourceTemplate.fileRealName
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public void setFilerealname(String filerealname) {
        this.filerealname = filerealname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceTemplate.uploadTime
     *
     * @return the value of ResourceTemplate.uploadTime
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceTemplate.uploadTime
     *
     * @param uploadtime the value for ResourceTemplate.uploadTime
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ResourceTemplate.remark
     *
     * @return the value of ResourceTemplate.remark
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ResourceTemplate.remark
     *
     * @param remark the value for ResourceTemplate.remark
     *
     * @abatorgenerated Tue Mar 20 16:57:46 CST 2012
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public String getFullPath() {
		// TODO 自动生成方法存根
		return getFiledir() + getFilerealname() ;
	}
}
